---
  engines:
    eslint:
      enabled: true
      channel: "eslint-3"
    fixme:
      enabled: true
    duplication:
      enabled: true
      config:
        languages:
        - javascript
  ratings:
    paths:
    - "src/**.js"
